### ISSUE TITLE
Sensitivity analysis 

### ISSUE THREAD

**Issue by Farzad-a** [scipopt/PySCIPOpt#351]
Hello, I have a question, I would appreciate your time to answer it or offer any alternative solution for it. I am trying to apply sensitivity analysis to my model. It means that after building the model and optimize it, I might change some parameters like lower bound or upper bound and want to solve the problem again. I could do this in CPLEX, but in SCIP when I call chgVarUb function after calling the optimized method, I get an error that I call chgVarUb in a wrong situation. I do not want the model solve my problem from scratch since it is too time consuming.
Thank you very much.

**Comment by mattmilten** [comment]
Hmm, I suppose you would have to implement this via a callback. You could write a ConstraintHandler callback that checks incoming solutions for optimality, i.e. a small enough MIP gap, and then runs the sensitivity analysis.
SCIP usually runs the optimization only once and cleans up most data structures in the end. You would need to stop SCIP before it's done.

**Comment by Farzad-a** [comment]
@mattmilten  Thank you so much for your reply. First of all, I should say that I tried model.setRealParam('limits/gap', 0.1), but it does not work.
I tried to implement what you said but there are some questions about that.
I used mode.getGap(), but unfortunately it only works when the optimization is done.
How else can I check the gap in constraint handler, and if the optimization satisfies the gap, and how should I stop it from further solving without scip erasing the model?

**Comment by ambros-gleixner** [comment]
Hi @Farzad-a ! We are just having a similar thread on the mailing list:  http://listserv.zib.de/pipermail/scip/2020-May/003977.html  (You can register for the mailing list on www.scipopt.org).  The reoptimizatoin feature of SCIP, however, only allows changes to objective function and restriction of bounds.

So very generally, I do not see an alternative to solving each MIP from scratch.  Also I am not aware that other solvers such as CPLEX would allow this. In this case you need to call freeTransform() after the optimization.  Then all data  from the solving process is deleted, but the problem is kept. Then you are allowed to modify the problem, e.g., by chgVarUb(), and call optimize() once more.

Please report back whether this answers your question.
