### ISSUE TITLE
Branch-and-price in pySCIPopt

### ISSUE THREAD

**Issue by RicardoGazquez** [scipopt/PySCIPOpt#394]
Hi all!

I am new to SCIP and am trying to learn how to use SCIP with pySCIPopt. I am very interested in using the branch and price rule with SCIP.
Thank you Felipe for your answer on the SCIP list.
A few days ago I tried to compile this example but failed to get it working. It is very likely that the error is mine.
https://github.com/SCIP-Interfaces/PySCIPOpt/blob/use-probdata-to-store-model/tests/test_coloring.py

I am trying to learn how to run these programs with branch-and-price rule, maybe you have a more correct example for my purpose.

Sorry for the inconvenience.

Thank you very much.
Regards.

**Comment by fserra** [comment]
This is not your fault. That code is not going to compile with the current PySCIPOpt. Sadly, I haven't had the time to rewrite for it to be compatible with the current version.
However, you can still use it as a guide to inspire your implementation. And to run something you can have a look at any example, those should work.

I think @purin0604, you also looked at this example. I don't know if you compiled it?

**Comment by purin0604** [comment]
I think the test_coloring.py example is incomplete, or at least the current PySCIPOpt doesn't have model attributes used in the example. (ex: model.repropagateNode)
However, as fserra said, it is very useful to learn how to use SCIP framework for Branch and Price algorithm. 
Since PySCIPopt is basically made by wrapping the original SCIP code written in C, I learned how to add pricer from the SCIP website (https://www.scipopt.org/doc-7.0.1/html/PRICER.php ). 

You can find all the model attributes that are supported in the current PySCIPOpt in `scip.pyx`  and the function names of pricer object in `pricer.pxi `file of pyscipopt folder.   

Besides test_coloring.py,  test_pricer.py could be helpful.

**Comment by RicardoGazquez** [comment]
Sorry for my delay in responding. Thank you very much for your responses.

I will try to learn with your recommendations.
Again, thank you all.

Regards.
