### ISSUE TITLE
Executing existing diving heuristic when condition is met.

### ISSUE THREAD

**Issue by vincentfortin** [scipopt/PySCIPOpt#407]
I am working on a MCTS based primal heuristic in python using Pyscipopt. 

I am looking for a way to call simple heuristics (like coef diving) inside the branchexeclp function loop. I know multiple diving heuristics are implemented in SCIP and are called depending on their priority, however I can't find in the documentation a solution to execute a specific heuristic if a certain criteria is met.

If you could point me to an example of some ressources, I would greatly appreciate it.

**Comment by fserra** [comment]
Hi.  Sorry for the unhelpful reply.

As far as I know this is not possible.

Since the execution method of most diving heuristics looks like
```c
   SCIP_HEURDATA* heurdata;
   SCIP_DIVESET* diveset;

   heurdata = SCIPheurGetData(heur);
   diveset = SCIPheurGetDivesets(heur)[0];

   SCIP_CALL( SCIPperformGenericDivingAlgorithm(scip, diveset, heurdata->sol, heur, result, nodeinfeasible, -1L, SCIP_DIVECONTEXT_SINGLE) );
```

I guess you could reproduce that in your branching rule. I suspect that one would need to extend the interface to allow for this (I don't know if there are already data structure for `DIVESET` and methods for getting them.
However, I don't really know if this can produce some nasty side effects.

That, unless @stephenjmaher or @mattmilten can come up with a different solution

**Comment by mattmilten** [comment]
Nope, sorry. I don't have another solution to this problem.
