### ISSUE TITLE
segment fault when writeLP

### ISSUE THREAD

**Issue by whille** [scipopt/PySCIPOpt#450]
segmentation fault, when calling writeLP()

codes:

from pyscipopt import Model
model = Model("test")
x = model.addVar()
y = model.addVar()
model.addCons(x + y == 32)
model.setObjective(x + y, "minimize")
model.writeLP('./Lp.lp')

**Comment by fserra** [comment]
Hi

Thanks, this should probably not segfault but die more gracefully. 
You can also compile in debug mode, most likely an assert will be raised there.
If you want to write your problem you need to use `model.writeProblem`

I guess the problem is that the LP doesn't exist.
Even if your model is an LP, SCIP doesn't really know this. 
The LP is only constructed when solving the LP relaxation.
Actually, you can only call `writeLP` when SCIP is in SOLVING stage.
