### ISSUE TITLE
Question about reoptimization

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [scipopt/PySCIPOpt#464]
Hello, 

I am trying to use the reoptimization function, but I am not sure if I coded in the right way. 
I still face an issue saying "SCIP: method cannot be called at this time in solution process!"
I attached the screenshot of the code. Your feedback would be really appreciated. 

![image](https://user-images.githubusercontent.com/70441233/102851362-a46d4e80-43e9-11eb-8508-58e50d815aee.png)

Thank you in advance for your help!

**Comment by fserra** [comment]
hi

I guess you need to first free the reoptsolve and then chg the objective.

If you look at the documentation in SCIP it will tell you in which stages the method can be called. So the documentation of free reopt solve says that if the problem is solved then the stage is going to be presolved. The documentation of chgreoptobjective says that it can only be called in presolved or problem stage

**Comment by IngyuLeeGitHub** [comment]
Thank you so much. It is working fine!
