### ISSUE TITLE
Error installing scipoptsuite-7.0.3

### ISSUE THREAD

**Issue by xtjjyygy** [scipopt/PySCIPOpt#531]
hello

when l running 'cmake -DCMAKE_INSTALL_PREFIX=$SCIPOPTDIR ..'，The following problems have occurred. I hope to get your help：

CMake Error at /opt/cmake-3.13.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Readline (missing: Readline_INCLUDE_DIR Readline_LIBRARY)
Call Stack (most recent call first):
  /opt/cmake-3.13.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  scip/cmake/Modules/FindReadline.cmake:39 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  scip/CMakeLists.txt:263 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.xev1eowaVh/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "/tmp/tmp.xev1eowaVh/cmake-build-debug/CMakeFiles/CMakeError.log".

Thank you

**Comment by xtjjyygy** [comment]
Need your help, thank you!

**Comment by CGraczyk** [comment]
Hi,
Please follow the Instructions [here](https://www.scipopt.org/doc/html/md_INSTALL.php) closely when installing SCIP.
Afterwards please provide more information about what you have tried to fix this issue on your end, otherwise it is not really possible to help you.

If you have additional questions about SCIP, send an email to the scip mailing list (scip@zib.de), since we only provide support for the python API here.

**Comment by mattmilten** [comment]
This is a SCIPOpt installation issue and should not be discussed here.
