### ISSUE TITLE
Delete node from node pool

### ISSUE THREAD

**Issue by dxyzx0** [scipopt/PySCIPOpt#629]
Is it possible to delete a node from the node pool, which means I want to remove a subtree?

**Comment by Joao-Dionisio** [comment]
This does not answer your question, but do you think that using [addConsLocal()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#aa3736da2061631bdfab21b1a1ba51af2) on the node you want to delete in order to make the subtree infeasible could be a workaround?

**Comment by dxyzx0** [comment]
> This does not answer your question, but do you think that using [addConsLocal()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#aa3736da2061631bdfab21b1a1ba51af2) on the node you want to delete in order to make the subtree infeasible could be a workaround?

Thanks, I think it's a valid workaround. I transfer from cplex to scip, since imo scip maybe has an official or safer way to do this.
BTW, do you know how to save all the constraints in the current node?

**Comment by Joao-Dionisio** [comment]
I am very happy to hear that, feel free to keep asking questions!

As for your second question, you are asking how you can access the constraints at a certain node in order to them save them, right? If that's the case, maybe you can use [getAddedConss()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Node.html#a854cc4c678667475cf4a194241439bae), which is a method in the Node class that gives you the constraints added at the node. Perhaps that combined with [getConss()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#ae51fe5bbf00b32c28f7582ccfb1ee9b2), which gives you the constraints of the model, can give you what you need.

After having the constraints, it should be straight forward to save them, I believe. 

Sorry if I misunderstood your question. I am also not an expert in PySCIPOpt, so sorry if it's not helping!

**Comment by dxyzx0** [comment]
> I am very happy to hear that, feel free to keep asking questions!
> 
> As for your second question, you are asking how you can access the constraints at a certain node in order to then save them, right? If that's the case, maybe you can use [getAddedConss()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Node.html#a854cc4c678667475cf4a194241439bae), which is a method in the Node class that gives you the constraints added at the node. Perhaps that combined with [getConss()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#ae51fe5bbf00b32c28f7582ccfb1ee9b2), which gives you the constraints of the model, can give you what you need.
> 
> After having the constraints, it should be straight forward to save them, I believe.
> 
> Sorry if I misunderstood your question. I am also not an expert in PySCIPOpt, so sorry if it's not helping!

Thanks. I think the function [getAddedConss()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Node.html#a854cc4c678667475cf4a194241439bae) only return the constraints added at this node instead of all the constraints w.r.t. the root node. Hence, if I want to remove the node and save all the information in the node, I need to recursively backtrack from the current node to its parent node, until hit the root node, and collect all the `AddedConss`. Is it correct?

**Comment by Joao-Dionisio** [comment]
Checking the documentation, I can't find a way to do it more directly, but that does seem to be an annoying way to solve your problem. 

@fserra , do you know of a better way to do this? (Sorry for tagging you)

**Comment by dxyzx0** [comment]
@Joao-Dionisio Sorry, more naive questions. When can I use the [getAddedConss()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Node.html#a854cc4c678667475cf4a194241439bae)?
The doc says it's a method of the `Node` class, but it seems not clear that where and when I can access the node. Sorry, I cannot find examples or docs about how to do this.

**Comment by Joao-Dionisio** [comment]
Hey @dxyzx0! No need to apologize, and the questions are not naive at all, I had no clue how to answer them :)

1. I haven't done what you are asking for, but I believe you may be able to do it in other places. I think that during branching it's the most obvious one. You can define a custom branching rule where you do all the things you want to, check [test_branch_probing_lp.py](https://github.com/scipopt/PySCIPOpt/blob/master/tests/test_branch_probing_lp.py). In a branching rule you need to use the [createChild](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#acdf72a74761eead25a152f077c26bfc0), that returns a ```Node``` object. In this case you should probably know which constraint you are adding right out of the gate, but you also have access to the nodes. 

2. I think the best way would actually be during branching, when the nodes are being created. But again, I'm also kind of a newbie, so don't trust what I say 100%!

3. I am not sure, but I am fairly confident that for that you would need to build PySCIPOpt and/or SCIP from source, instead of using Anaconda and the pre-compiled packages. On the web there are some presentations and the documentation goes a bit into it as well, it may help out as well. Oh, and also the several papers of the SCIP releases!

Now that I think about it, I think in a custom branching rule you may also be able to check which constraints have been added, by comparing the "local model" with the original one, but I don't know of a way to do it explicitly.

**Comment by dxyzx0** [comment]
@Joao-Dionisio Thanks a lot. 
1. What if I want to save and delete the node, when scip receive certain external information？ Say, Someone sends a deleting signal to scip.
2. Is it possible to communicate with scip during the solving process？ I think the eventhdlr may do this job.

**Comment by Joao-Dionisio** [comment]
@dxyzx0 
1. Someone other than yourself when you are running the code? Hermm... for that I have no idea, but I imagine that it's possible. I think people on SCIP itself will be better suited to answer it. Check out the [contacts](https://scipopt.org/index.php#contact) on their page.
2. I know that it is possible to write code that will alter the solving process of SCIP (with branching rules, constraint handlers, etc.), but if SCIP can receive messages at runtime, that I don't know, and it may be related to the answer of question 1.
3. And once again, it will depend on what you are asking. If you are able to define the node selection prior to running the code, then yes, you can define custom node selectors and define their priorities. See the [documentation](https://www.scipopt.org/doc/html/NODESEL.php). If you want to create a new node selector while SCIP is running, I've never tried to do it, but maybe one can do it inside a previous node selector? I am just guessing here, but I think the SCIP guys will know.

Sorry for not being able to help much!

**Comment by dxyzx0** [comment]
Thanks a lot. 

> @dxyzx0
> 
> 1. Someone other than yourself when you are running the code? Hermm... for that I have no idea, but I imagine that it's possible. I think people on SCIP itself will be better suited to answer it. Check out the [contacts](https://scipopt.org/index.php#contact) on their page.
> 2. I know that it is possible to write code that will alter the solving process of SCIP (with branching rules, constraint handlers, etc.), but if SCIP can receive messages at runtime, that I don't know, and it may be related to the answer of question 1.
> 3. And once again, it will depend on what you are asking. If you are able to define the node selection prior to running the code, then yes, you can define custom node selectors and define their priorities. See the [documentation](https://www.scipopt.org/doc/html/NODESEL.php). If you want to create a new node selector while SCIP is running, I've never tried to do it, but maybe one can do it inside a previous node selector? I am just guessing here, but I think the SCIP guys will know.
> 
> Sorry for not being able to help much!

The node selection is predefined, but changing the nodelsel priority during the solving process, instead of predefined priority, is possible?

P.S:
For anyone who tries to implement the [addConsLocal()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#aa3736da2061631bdfab21b1a1ba51af2), according to [here](https://github.com/scipopt/PySCIPOpt/issues/416#issue-683707106), it has functionality limitations.

**Comment by Joao-Dionisio** [comment]
> The node selection is predefined, but changing the nodelsel priority during the solving process, instead of predefined priority, is possible?

I believe so. Depending on when you want to do it, imagine that you want to alter it every time you branch, I think you would just need to add a new node selector after the branching occurs. You would also need to delete the old node selector, but I haven't found a way to do it in PySCIPOpt, though I imagine it would be possible.

Checking SCIP's documentation, I could find the method [SCIPnodeselSetData()](https://www.scipopt.org/doc/html/group__PublicNodeSelectorMethods.php#ga0c79cf659c11d6d73a073ce16bb2f7b4), that allows you to change the data of the node selector, which would do what you want, I believe. Unfortunately, I think it still hasn't been brought over to PySCIPOpt, or at least I can't find it. 

Thanks for bringing me the attention to the problems with addConsLocal()! PySCIPOpt still has quite a bit of issues when compared to SCIP. I want to start looking at improving the code itself in the near future, as I've been focusing only on helping people with the functionalities of PySCIPOpt. Unfortunately, I've never done anything like it before, and I also have my own work to do, so I won't be able to solve these issues quickly, I'm afraid.

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you still have problems!
