### ISSUE TITLE
can't find LP file

### ISSUE THREAD

**Issue by HorizonLiang** [scipopt/PySCIPOpt#632]
```
from pyscipopt import Model
model = Model("Example")

x = model.addVar("x")
y = model.addVar("y", vtype="INTEGER")
model.setObjective(x + y)
model.addCons(2*x - y*y >= 0)
model.optimize()

model.writeLP("./model.lp")
```

I can't find the LP file, while runing the code showing above.

**Comment by Joao-Dionisio** [comment]
Thank you for opening the issue! Apparently there's something wrong with writeLP(), since the code silently exits while trying to run it. So it isn't actually writing the LP, that's why you can't find it. Alternatively, you have [writeProblem()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#aaeea39150fbf007180b7ab7d8e476d2e), but I don't know if it does what you want...

**Comment by Joao-Dionisio** [comment]
Thanks, @fserra! There are quite a bit of issues related (even if indirectly) to PySCIPOpt's error handling. I will try to take a look at it in the future.

**Comment by fserra** [comment]
yes, this is a bit annoying... I guess that ideally one would develop using the underlying scip in debug mode (then a lot more errors would pop up), but that might be too much to ask. An alternative is to start duplicating the checks that already exist in scip, e.g., add something like
```
        if not self.getStage() == SCIP_STAGE_SOLVING:
            raise Warning("method can only be called in solving stage")
```
I don't know what is worse

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you still have problems!
