### ISSUE TITLE
Warning: SCIPgetSolVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)

### ISSUE THREAD

**Issue by prachishah6795** [scipopt/PySCIPOpt#644]
Hi ! 

I am getting this warning when trying to use model.getVal() after using model.optimize(). 

Warning: SCIPgetSolVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)

According to SCIP documentation, stage 10 seems to the SOLVED, but the above message mentions stage SOLVING. I am confused by this output. Could you please help? Thanks!

**Comment by Joao-Dionisio** [comment]
Hello, @prachishah6795 ! I think you found an error in the error messages :) I believe it has been fixed on the most recent branch (you can see the pull request #581 for more insight). What the error message should say is:

```
Warning: SCIPgetSolVal can only be called with a valid solution or in stage SOLVING (current stage: 10)
```

Now, regarding your actual problem, stage 10 is indeed the SOLVED stage. But SOLVED means that either SCIP found the optimal solution, proved that the problem is unbounded, or proved that it's infeasible. Is there a possibility that the model is infeasible when you are trying to call model.getVal()? Did SCIP find a solution?

**Comment by prachishah6795** [comment]
Hi @Joao-Dionisio ! 

Thank you for such a quick response. That's very helpful. The model was infeasible, so that explains.
