### ISSUE TITLE
Using a decision variable as index of an array

### ISSUE THREAD

**Issue by andreafresa** [scipopt/PySCIPOpt#679]
Hi everyone, I have an objective function where the decision variable is the index of an array. Thus, based on the value of this index I take a different value of a discrete function. This affects the decision of the solver for maximizing the objective function. 
Is there a way of using a decision variable as an index of an array?
Alternatively, I defined a decision variable that is 1 if the value "i" of the discrete function must be taken, and 0 otherwise, but this means that the number of decision variables increases to N, which is the number of discrete points in the function and affects the solving time.

**Comment by Joao-Dionisio** [comment]
Hello, @andreafresa! Just to see if I understood correctly. You have multiple potential objectives, and a decision variable will state which will be applied, right? And what you managed to do was:

$$ \max_{i,x} \sum_{j=1}^N i_j \times f_j(x) $$ 

I just had a really dumb idea, but it might work for your purpose. However, the problem is not linear, so it may also end up being worse. What about doing something like this:

$$ \max_{i,x} \sum_{j=1}^N  \left(f_j(x) \times \frac{\prod_{t \neq j} (t-i)}{\prod_{t \neq j} (t-j)}\right) $$

**Comment by andreafresa** [comment]
I have not understood completely your idea, but the formulation is something like this:

$max_{x}\sum_{i \in I}f_i({x_i})$

As you can see the decision variable is x_i. I know the function is not linear, but my decision variable is an integer, so what is the problem here?

**Comment by Joao-Dionisio** [comment]
Hello, @andreafresa, sorry for the delay. For added context, is this issue a continuation of #666?

You are trying to maximize a sum of functions over a set $I$, and only one of them must be active at a time, right? That is, at each moment, you only have one specific $f_i$, the others must be $0$. You tried to add additional binary variables, let's call them $k$, such that $k_i=1$ if you want $f_i$ to be active and $k_i=0$ otherwise. Thus, you have $\sum_{i \in I} f_i(x_i)\times k_i$, right? My suggestion was (and note that I think what you did may be better) to use a single integer variable $k$ such that $k=i$ if we want $f_i$ to be active. The way I did this was like this

 $$\sum_{i \in I} f_i(x_i) \times \frac{\prod_{t \neq i} (t-k)}{\prod_{t \neq i} (t-i)}$$

An example may help in understanding why this works. Suppose that I is the set {1,2,3}. We have functions $f_1,f_2,f_3$ and suppose also that at some point $k=3$, meaning $f_3$ is supposed to be active and $f_1,f_2$ inactive. Then the objective function is

$$ f_1(x_1) \times \frac{(2-3)(3-3)}{(2-1)(3-1)} + f_2(x_2) \times \frac{(1-3)(3-3)}{(1-2)(3-2)} + f_3(x_3) \times \frac{(1-3)(2-3)}{(1-3)(2-3)} $$

Which simplifies to $f_3$, as the first two terms are $0$ and the last fraction is equal to $1$.

I found similar discussions on the [AMPL mailing list](https://groups.google.com/g/ampl/c/HmIZqetimJ8) that suggests your initial approach, and on [MSE](https://math.stackexchange.com/questions/2417504/can-we-define-an-indexing-set-using-a-variable-in-the-optimization-problem) that has some more discussion.

As for why this can't be done directly... I can't give you a satisfying answer, but I don't think it's SCIP specific, I think it may have to do with the constraint optimization paradigm we are used to. But if someone reading this may provide a better insight, please do!
