### ISSUE TITLE
Solving linear programming

### ISSUE THREAD

**Issue by rlacjfjin** [scipopt/PySCIPOpt#708]
Hello,
Is it possible to use pyscipopt do that:
   when I solve the linear programming, because of my wrong input data, the problem is infeasible. But I want to do something about the reasons such that: 1. computeIIS such as gurobi   2. can get some solution with relaxation of original problem.
 And some orther actions which can I do?

Please give me some help, thanks..

Zhe

**Comment by Joao-Dionisio** [comment]
Hello, @rlacjfjin, sorry for the delay in my answer! I think PySCIPOpt doesn't have something like computells in gurobi, but SCIP may have it. Take a look at Issue #697, I think it's the same (unresolved) issue.

I will be closing this one since it seems to be a duplicate, but if you think it makes sense, feel free to reopen it!
