### ISSUE TITLE
Cannot addVar after solving and freeTransform with pricedVars

### ISSUE THREAD

**Issue by igorbanfi** [scipopt/PySCIPOpt#755]
Hello

**Describe the bug**

After solving the model with pricer and running freeTransform, pricedVars created during solution process are deleted from scip instance, but _modelvars is not updated. When trying to add a new variable to the model with addVar, assertion error is thrown

```
  File "***/example.py", line 162, in <module>
    s.addVar("x", vtype = "C", obj = 1.0)
  File "src/pyscipopt/scip.pyx", line 1468, in pyscipopt.scip.Model.addVar
AssertionError
```
In provided example 4 variables are added without an issue, but when adding the fifth the exception is raised.

**To Reproduce**
[Example](https://gist.github.com/igorbanfi/b143ffde19f6fa06048d40a483abd034)
Derived from _tests/test_pricer.py_ 

**System**
 - OS: Ubuntu 22.04
 - Version 4.3.0
 - SCIP version 8.0.4

**Comment by igorbanfi** [comment]
A solution to the issue is to recreate _modelvars after freeTransform
323212ed5519da3480e7f642091ed84854d28cfb

**Comment by Joao-Dionisio** [comment]
Hey @igorbanfi! Thanks for the detailed issue and the PR. I've been trying to go over what's going wrong, and indeed I think it's trying to access ```self_modelvars``` after free transforming. Someone else may accept your PR (I can't). Maybe this is something that could be accomplished without deleting and getting the variables again.

But, when it comes to fixing the issue it works great, and it may clear other open issues, so that's awesome!

**Comment by igorbanfi** [comment]
Hi. I agree it would be better if _modelvars is modified before running freeTransform. Opened a PR.

**Comment by Joao-Dionisio** [comment]
PR #757 solves this issue. Thanks for the help, Igor!
