### ISSUE TITLE
only adds the cut planes at the root node

### ISSUE THREAD

**Issue by zslztms** [scipopt/PySCIPOpt#763]
How do I set the parameters so that the SCIP only adds the cuts plane at the root node？
Does pyscipopt provide such a parameter interface?

**Comment by Joao-Dionisio** [comment]
There may be other, simpler, ways to do it, but I think I managed to do what you wanted. You create an event handler that gets activated whenever you go to a new node, and disable separators if it's not the root node. I'm unsure whether the root node is solved multiple times, that's why I change the settings back to the default values.

```
from pyscipopt import Model, SCIP_PARAMSETTING, Eventhdlr

class disableCuts(Eventhdlr):

    def __init__(self, model):
        self.model = model

    def eventinit(self):
        self.model.catchEvent(SCIP_EVENTTYPE.NODEFOCUSED, self) # the event is called whenever a node is about to be solved

    def eventexec(self, event):
        if self.model.getCurrentNode().getDepth() > 1: # if we aren't in the root node
            model.setSeparating(SCIP_PARAMSETTING.OFF) # disable separators
        else:
            model.setSeparating(SCIP_PARAMSETTING.DEFAULT) # return to default values

model = Model()
model.includeEventhdlr(disableCuts, "Cut disabling Eventhdlr", "Event Handler for disabling cuts except at root node") 
``` 

I don't know if it matters to you, but if you also want to disable propagation (which would fix variables during the solving process), then you also need ```model.disablePropagation()```. I didn't run this code, so there might be some syntax issues, but the idea should be correct. Let me know if this helps!

**Comment by Opt-Mucca** [comment]
@zslztms @Joao-Dionisio This can be achieved in a much simpler way:
``model.setParam("separating/maxcuts", 0)``

**Comment by zslztms** [comment]
> @zslztms @Joao-Dionisio This can be achieved in a much simpler way: `model.setParam("separating/maxcuts", 0)`
> 
> This will disable SCIP from adding any cuts after the root node, but cuts can still be added at the root node.

Thanks,that's the answer I was looking for. Out of curiosity, I still want to know what parameter should I use to disable all cut planes, like use `model.setParam()`.

**Comment by Opt-Mucca** [comment]
To be complete sure that no cuts will ever be created or added:
```model.setParam("separating/maxcuts", 0)
model.setParam("separating/maxcutsroot", 0)
model.setParam("separating/maxrounds", 0)
model.setParam("separating/maxroundsroot", 0)```

**Comment by zslztms** [comment]
> @zslztms @Joao-Dionisio This can be achieved in a much simpler way: `model.setParam("separating/maxcuts", 0)`
> 
> This will disable SCIP from adding any cuts after the root node, but cuts can still be added at the root node.

I found that the cut planes selector(use `model.includeCutsel()` to observe) was still called many times after limiting the cut plane to the root node only. This means that the cut planes is added at **many** root nodes. I have some questions about that
1. Because scip builds multiple search trees, there are multiple root nodes. But how do these search trees work together?
2. Perhaps because a search tree in scip has multiple root nodes. What is the definition of the root node.

**Comment by Joao-Dionisio** [comment]
@zslztms, did you check the node number whenever the cuts were being added? Are they being applied to different nodes or to the same one?

It's better to wait for Mark's input, as I'm really not sure how this works, but during the search process, I believe new information may make it so that returning to the root node and adding cuts based on this information makes sense, enabling a tighter linear relaxation. (This explanation might be completely incorrect, however.)

I don't know how it works, but SCIP also sometimes restarts the search, maybe it also has an impact.

Maybe SCIP's page on [how to add separators](https://www.scipopt.org/doc/html/SEPA.php) might help a little bit.

**Comment by sbolusani** [comment]
@zslztms There are at least two different reasons why the cutting plane selector can be called multiple times despite limiting cuts to the root node.

1. SCIP can call separators multiple times in the root node itself. If significant changes happen (due to various components of SCIP) in the root node relaxation after a round of separation call, then the separators may be called again in the root node. This can result in follow up calls to the cutting plane selector.
2. SCIP has the ability to restart the instance solving for various reasons (as mentioned above by @Joao-Dionisio), such as, the estimated remaining tree size is too large or good number of global fixings have happened recently, among other reasons. Whenever a restart occurs, a new tree is constructed on the reduced instance resulting in a new root node. So, the separators may be called again in this root node along with a follow up call to the cutting plane selector.

> Because scip builds multiple search trees, there are multiple root nodes. But how do these search trees work together?

As mentioned above, the multiple search trees are due to restarts (that happen sequentially). SCIP knows/stores the relationships between the instances solved via restarts. So, towards the end of the instance solving, SCIP can get solution values of the original instance using these relationships.

> Perhaps because a search tree in scip has multiple root nodes. What is the definition of the root node.

At any given point in solving, there is only one root node belonging to one ongoing tree.

Here is an additional parameter that may be useful: `separating/maxroundsrootsubrun = 0` will set the maximal number of separation rounds in the root node of a subsequent run (i.e., a restart) to zero. Then, the separators will be called in the first run/tree only.

**Comment by zslztms** [comment]
I would like to know more about scip parameters. Where can I find all the parameter information, such as a document or a piece of code, including optional parameters and their explanations?

**Comment by abb-omidi** [comment]
@zslztms,

Maybe someone from SCIP side can introduce the reference, but at least as far as I know the following would be the good starting points:

1) [List of SCIP Parameters](https://www.scipopt.org/doc/html/PARAMETERS.php)

2) [PySCIPopt documents](https://scipopt.github.io/PySCIPOpt/docs/html/md_README.html#autotoc_md0)

3) SCIP mailing list
