### ISSUE TITLE
37529 illegal hardware instruction after upgrade PySCIPOpt to Version 4.4.0

### ISSUE THREAD

**Issue by vale46** [scipopt/PySCIPOpt#767]
**Describe the bug**
I recently upgraded `pyscipopt` to v4.4.0 on Debian Linux running Python 3.11. When I call the SCIP MIP optimizer, seeing this error:
**37529 illegal hardware instruction**. Downgrading to v4.3.0, the code works as expected.

**To Reproduce**
Upgrade `pyscipopt` to v4.4.0

**System**
 - OS: Debian Linux
 - Version Bookworm
 - SCIP Version 8.1.0
 - How did you install `pyscipopt`? pip

**Additional context**
I suspect this issue relates to my Intel CPU Version i7-3770 CPU @ 3.40GHz. Since these CPU are quite aged, I had the same error after upgrading `python-polars` (https://github.com/pola-rs/polars/issues/11692). Luckily `polars` makes a version of its library called `polars-lts-cpu` available to get around this. Is it possible that newer versions of `pyscipopt` can be made available to support older gen CPUs?

Thank You

**Comment by Opt-Mucca** [comment]
Is it possible to copy the error message here?

To give a summary of what the problem most likely is: From v4.4.0, when using pip to install PySCIPOPt, a new version of SCIP is automatically installed in the back end and used. This version was compiled on manylinux2014 (https://github.com/pypa/manylinux), and what I thought was a pretty old Intel CPU, but I didn't account for any hardware errors. So thanks for bringing up this issue. After seeing the error message I can try and fix it (although it might take a while. I'm still struggling to support ARM right now).

The short-term fix: When using v4.3.0 you had to be linking against some SCIP installation. If you download the repository with the v4.4.0 flag, you can just build PySCIPOpt from source with `python -m pip install .` while the `SCIPOPTDIR=...` environment variable is set. This should bypass the SCIP installation that is now shipped when you use PyPI.

**Comment by vale46** [comment]
> Is it possible to copy the error message here?
> ...
> The short-term fix: When using v4.3.0 you had to be linking against some SCIP installation. If you download the repository with the v4.4.0 flag, you can just build PySCIPOpt from source with `python -m pip install .` while the `SCIPOPTDIR=...` environment variable is set. This should bypass the SCIP installation that is now shipped when you use PyPI.

thanks for your feedback and suggested workaround. I was able to build/install PySCIPOpt v4.4.0 locally against my SCIP installation, and successfully run my script.

However, when I install PySCIPOpt v4.4.0 thru pip, I don't see any detailed errors when running my script on command line - other than the generic "Illegal hardware instruction". My use case is solving a MIP specified using CVXPY which in turn calls the SCIP solver under the covers - hence I don't `import pyscipopt` and its functionality explicitly in my Python code. But I was able to load/test PySCIPOpt v4.4.0 with sample code that's available in the project's github repository. So I will need to further investigate the CVXPY interface which is calling the SCIP solver, to pinpoint where the error occurs.

Can you suggest if there's a different approach I can take to produce detailed error message when running my code.

**Comment by Opt-Mucca** [comment]
Glad that the solution worked! For now I think this will have to be the method that you use to install PySCIPOpt (unless it becomes a common error).

I'm not sure how to get a more detailed error message with this issue, but would appreciate if you could. From my understanding this error is occurring during the actual solving process of SCIP. So the installation is fine (if you can `import pyscipopt` and run some tests). This just means that the SCIP version that is shipped with PyPI is compiled on some newer machine and at some point runs some code that cannot be translated to be understood by your CPU. 
I'm really not sure what the fix here is, because I am against supporting hardware / OS's well outside of their support cycles, and I'm not even sure if I can get PyPI to dynamically install different versions depending on the age of the CPU. 
I will include someone here who has more of a clue, and who might know an easy fix: @svigerske

**Comment by svigerske** [comment]
I could imagine that one gets this if using some `-march` compiler flags with C/C++, which tells the compiler to generate code for a specific architecture, therefore producing something that won't run on older architectures. You may want to go through your build logs if you find something like that. We don't have this in SCIP with the normal makefiles (we use `-mtune=native`), but I cannot say for sure what the cmake system produces.

However, since there are so many libraries involved, it might be more useful to first run a debugger to see where this instruction resides.

**Comment by Joao-Dionisio** [comment]
Hey @vale46, I'm closing this issue to clear the issue page, but feel free to reopen if you're still having problems!
