### ISSUE TITLE
The value of model.getNNodes() changes from 1147 to 0 during the solving process

### ISSUE THREAD

**Issue by hongxuanrui1999** [scipopt/PySCIPOpt#779]
When solving a milp problem, the value of model.getNNodes() suddenly drops to 0.

global primal bound: 13558.169415357383
model.getNNodes(): 1146, len(l): 24, len(s): 1, len(c): 0

global primal bound: 13558.169415357383
 self.model.getNNodes(): 1147, len(l): 24, len(s): 0, len(c): 0

global primal bound: 13558.169415357384
model.getNNodes(): 0, len(l): 1, len(s): 0, len(c): 0

global primal bound: 13576.254399273943
model.getNNodes(): 1, len(l): 0, len(s): 0, len(c): 2

**Comment by Opt-Mucca** [comment]
So what is probably happening (which should be very visible from the output during `optimize`):
SCIP has performed a restart. For example, SCIP does this when it thinks the problem is going to be too difficult to solve in its current state, and that it can gain performance by applying new cuts / deciding on new early branching decisions. The function `self.model.getNNodes()` returns the number of nodes of the current run, which after a restart is 0 or 1 depending on when exactly you query the model. For a monotonically increasing number of nodes that includes those involved in previous restarts, use the function `self.model.getNTotalNodes()`

**Comment by hongxuanrui1999** [comment]
Thank you very much! I think your answer is correct.
