### ISSUE TITLE
Does SCIP support multi-objective when build model?

### ISSUE THREAD

**Issue by chiangwyz** [scipopt/PySCIPOpt#825]
There is a model with three sub-objective, one is for mimimize cost, and another one is for maximize efficiency, and the rest is for maximize score. I want to know does SCIP have multi-objective API, such as Blended Objectives method or Hierarchical Objectives?
Thanks all.

**Comment by Joao-Dionisio** [comment]
Hello, @chiangwyz! There is [PolySCIP](https://polyscip.zib.de/), but it seems it hasn't been updated in a while...

There's also [this](https://www.scipopt.org/doc-3.2.0/applications/MultiObjective/) application, but I don't know if it interests you.

**Comment by chiangwyz** [comment]
@Joao-Dionisio Joao-Dionisio，thank you so much.

**Comment by leoneifler** [comment]
Just chiming in here: Blended objectives (if I understand the term correctly) is just a linear combination of the different objectives, right? That you can easily do yourself, I think. Hierarchical Objectives you can also do (although there is not direct support for it) in the following way:

1. Optimize under only the first objective -> save optimal objective value 
2. Add constraint of the type "first objective <= optimal value" (assuming minimization) and change objective to second objective
3. re-optimize and repeat until all objectives are done

This is obviously not the most efficient, but if your problem is not too hard, might be good enough.

PolySCIP will try to compute a Pareto-front of optimal solutions, which is much harder than the two cases you mentioned

**Comment by chiangwyz** [comment]
@leoneifler , thank you, it's so kind of you. You provide a very easy way to implement a hierarchical objectives in multi-objective, and I also want to do it in this way.
