### ISSUE TITLE
Min/Max function in PySCIPopt

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#826]
Dear support team, 

As far as I know, SCIP can deal with non-convex functions like $Max()$. Also, based on [this](https://github.com/scipopt/PySCIPOpt/issues/198) and [this](https://github.com/scipopt/PySCIPOpt/issues/524) answer, it seems these kinds of **_non_linear handler_** have not been implemented yet in PySCIPopt. 

Now, I am wondering if, is it possible to write these kinds of functions via PySCIPopt 5 directly, something like `model.addCons(y == max(x1,x2))` or if we have to use some linearization of the model, then feeding that into the solver?

Best regards

**Comment by Opt-Mucca** [comment]
It is not possible to write these functions directly using PySCIPOpt, because SCIP as the underlying solver does not have a `max` or `min` constraint handler.

As you stated however, SCIP can deal with general non-convex functions. Therefore, with some roundabout formulations of the existing constraint types (that do exist in PySCIPOpt), one can model a `max` function. I'll quickly give an example formulation, which is a subset of the argmax formulation presented in https://arxiv.org/abs/2312.08074

Let x be the input variables (say there are N of them), and y be the output variable (the max). We are going to introduce N slack variables denoted s_i and N binary variables denoted z_i. 

x_i + s_i - y == 0 \forall i \in N
SOS1(s_i, z_i) \forall i \in N
\sum z_i >= 1

In PySCIPOpt language:
```
for i in range(n):
    scip.addCons(y == x[i] + s[i])
    scip.addConsSOS1([z[i], s[i]])
scip.addCons(sum(z[i] for i in range(n)) >= 1)
```

There are many alternate formulations, most commonly ones that use big-M. In most cases bigM formulations are preferred and will have better performance, however they rely on having bound information of the variables. Please go see available resources online for further information on this.

**Comment by abb-omidi** [comment]
Dear @Opt-Mucca,

Many thanks for your answer. Also, the provided link is interesting to me, and I will read that ASAP.

Best regards

**Comment by Joao-Dionisio** [comment]
Hello @abb-omidi! Can this issue be closed?

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

At the moment I close it. If I have any further questions I will reopen it again. 🙏

Best
