### ISSUE TITLE
several tests failing against local build of master branch

### ISSUE THREAD

**Issue by ctdunc** [scipopt/PySCIPOpt#836]
**Describe the bug**
A few of the tests are failing against a local build of master. I am running the latest stable Debian in WSL. 

- `test_model > test_solve_concurrent` segfaults when built against scip compiled with `-DAUTOBUILD=on -DTPI=any` with soplex. This does not occur on the PyPI version as it is not built with TPI enabled.
- `test_model > test_locale` fails as `pt_PT` is an invalid locale.
- `test_nonlinear > test_addExprNonLinear` fails as `y=2.0000163858811364` instead of `2`. It may not be respecting the new epsilon?

**To Reproduce**
`pip install .;pytest`.
**Expected behavior**
Tests should pass.

**System**
 - OS: Debian GNU/Linux 12 (bookworm)
 - SCIP version: 9
 - How did you install `pyscipopt`? Locally

**Comment by Joao-Dionisio** [comment]
Hello, @ctdunc, thank you for the issue! Also, thank you for your other awesome issue, sorry for not saying anything. These are just general comments and don't really fix the issues. 

- I'm not sure whether I've ever run the parallelism tests since I usually compile SCIP without TPI, but it seems to be causing a bunch of issues (#780, among others)
- ```pt_PT``` is a valid locale (it's the one I have :) ), but it's not a standard one, I think you need to maybe install it somehow? This may work: ```sudo apt-get install tzdata locales -y && sudo locale-gen pt_PT && sudo update-locale```
- I had already noticed the ```test_addExprNonLinear``` one, but I assumed it was a problem with my machine, as it is passing on the pipelines. I have to look into it.

**Comment by ctdunc** [comment]
Thank you for clarifying. Mostly wanted to confirm that I was not creating these issues somehow with my local build or missing others in my PR on the other issue

**Comment by Joao-Dionisio** [comment]
No problem, @ctdunc! But I'll reopen the issue, since this is still something we need to look at :)
