### ISSUE TITLE
Version 5.0.0 has been removed from PyPI

### ISSUE THREAD

**Issue by SorianoMarmol** [scipopt/PySCIPOpt#863]
Version 5.0.0 has been removed from PyPI.

Our pipelines have stopped working.

Is there any reason for this removal? Why hasn't it been marked as junk?

Thank you in advance.

**Comment by Opt-Mucca** [comment]
Sorry for this...... We had to remove 4.4.0 and 5.0.0 because of conflicting licenses from code linked against SCIP and buried in the wheel. That's completely on us if it's screwed your pipeline, but we believe it was best to remove it ASAP.
The new version on PyPI `5.0.1` should be plug and play as usual. (Still an issue of symmetry now missing on windows builds, but that will be fixed in `5.0.2`)

**Comment by mmghannam** [comment]
Sorry about this, next time this happens we'll yank the version to avoid issues in downstream projects. Sorry for the inconvenience.
